[tool.poetry]
name = "qtnodes"
version = "0.0.1"
description = ""
authors = []

[tool.poetry.dependencies]
python = "3.12.5"
shiboken6 = "^6.7.2"
pyside6 = "^6.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"